[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID"
  VITE_FIREBASE_API_KEY = "AIzaSyAoJlC4b_Or6B4sTMKu9ZvefAozIos8zlY"
  VITE_FIREBASE_AUTH_DOMAIN = "kkgurudwara.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "kkgurudwara"
  VITE_FIREBASE_STORAGE_BUCKET = "kkgurudwara.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "575880260864"
  VITE_FIREBASE_APP_ID = "1:575880260864:web:91cec97e9b95dbce7ad7e5"
  VITE_SUPER_ADMIN_UIDS = "1sMid0KljubuX2PidFy84B2qDKy1"
